apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: dxp
spec:
  ingressClassName: nginx
  rules:
  - host: dxp.localdev.me
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- range .Values.extensions }}
  - host: {{ .name }}.localdev.me
    http:
      paths:
      - backend:
          service:
            name: {{ .name }}
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- end }}
  tls:
  - hosts:
    - dxp.localdev.me
    {{- range .Values.extensions }}
    - {{ .name }}.localdev.me
    {{- end }}